import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  appButton: {
    marginTop: 15,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: '100%',
    backgroundColor: '#481186bd',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  searchToggleButton: {
    marginTop: 15,
    marginRight: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#773eb9',
    borderRadius: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      web: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.18)',
      },
    }),
  },
  filtersButton: {
    marginTop: 15,
    // marginRight: 25,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#773eb9',
    borderRadius: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      web: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.18)',
      },
    }),
  },
  appButtonText: {
    color: '#fff',
    fontWeight: '600',
    textAlign: 'center',
  },
  linkText: {
    color: '#fff',
    fontWeight: '600',
  },
  cartButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 28,
    backgroundColor: '#773eb9',
    elevation: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
      },
      android: {
        elevation: 14,
      },
      web: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
        boxShadow: '0px 8px 20px rgba(0, 0, 0, 0.24)',
      },
    }),
  },
  cartButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  cartBadge: {
    marginLeft: 5,
    minWidth: 26,
    height: 26,
    borderRadius: 50,
    backgroundColor: '#481186bd',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  cartBadgeText: {
    color: '#ffffffbd',
    fontWeight: '700',
  },
});